theme: jekyll-theme-minima
minima:
  skin: dark
  date_format: "%Y-%m-%e, %H:%M"
header_pages:
  - about.md
  - projects.md
rss: rss
linkedin_username: bugra-birgili-500a7a57
show_excerpts: true
title: Bugra Birgili's personal website
description: Occasional content about computational chemistry and chemical engineering topics.
