remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
title: "Bugra Birgili's personal website"
description: "Occasional content about computational chemistry and chemical engineering topics."
lang: en-CA
url: blog.bugrabirgili.io
author: Bugra Birgili
header_pages:
  - about.md
  - projects.md
rss: rss
linkedin_username: bugra-birgili-500a7a57
github_username: bugrabirgili
show_excerpts: true
search: true
